### ISSUE TITLE
"Undefined columns" error subsetting sites_base in grts()

### ISSUE THREAD

**Issue by nstauffer** [USEPA/spsurvey#32]
I've run into an issue that appears to be a bug in how `grts()` is determining which variables exist in the object sites_base because it's returning the error "Error in [.data.frame(x, i, j, drop = drop) : undefined columns selected" after the call `subset(sites_base, select = c(add_names, sframe_names_good[-sframe_geometry_col], names(sframe_temp)))` on line 473.

That said, there's a non-zero chance that there's something malformed about my inputs because I've been able to use `grts()` without trouble for other sampling designs both before and after running into this issue.

I've attached a [zipped geodatabase](https://github.com/USEPA/spsurvey/files/10179726/example_strata.zip) containing the polygons I'm using as strata. The following code is what's returning the error:
```
frame <- sf::st_read(dsn = "whatever/pathway/to/the/gdb/example_strata.gdb", layer = "strata")
sample_design <- spsurvey::grts(sframe = frame,
                                n_base = c(`Crossman Peak` = 5, Planet = 7, Primrose = 4, `Alamo Crossing` = 4),
                                stratum_var = "stratum",
                                seltype = "equal",
                                n_over = c(`Crossman Peak` = 5, Planet = 3, Primrose = 3, `Alamo Crossing` = 3),
                                DesignID = "Site",
                                sep = "-")
```
I'm hoping it's just a mistake on my part!

**Comment by michaeldumelle** [comment]
Thanks @nstauffer, and sorry for the late response (I am out on parental leave). This bug will be fixed in the next version of spsurvey submitted to CRAN (the current version of spsurvey is v5.4.1). 

In the meantime, a workaround is to rename the variable you in `frame` called `"stratum"` to anything other than `"stratum"` (e.g., rename it to `"strata"`, `"stratum2"`, `"new_variable_name"`, etc.).

**Comment by nstauffer** [comment]
Thanks for patching it, @michaeldumelle! In the meantime I'll use that workaround.

**Comment by michaeldumelle** [comment]
@nstauffer this bug fix has been pushed to CRAN as part of v5.5.0.

**Comment by t-jacksonbue** [comment]
This bug remains in v5.5.1 when sampling a subset of a subset:

x <- c(0,0,1000,1000,0)
y <- c(0, 1000, 1000, 0, 0)

p <- st_polygon(list(cbind(x, y)))
p <- st_sfc(p, crs = 'epsg:3035')
p <- st_as_sf(p)

g1 <- grts(p, 100)
g2 <- grts(g1$sites_base, 20) #first subset works
g3 <- grts(g2$sites_base, 5) #second subset throws OPs error

#workaround by subsetting columns
g2b <- dplyr::select(g2$sites_base, siteID, x)
g3 <- grts(g2b, 5)

**Comment by t-jacksonbue** [comment]
The issue seems to be related to the number of columns. Selecting any columns from g2$sites_base up to a maximum of 10 works, but if 11 or more are selected it fails.
